// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addCartItemStmt, err = db.PrepareContext(ctx, addCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query AddCartItem: %w", err)
	}
	if q.clearCartStmt, err = db.PrepareContext(ctx, clearCart); err != nil {
		return nil, fmt.Errorf("error preparing query ClearCart: %w", err)
	}
	if q.createCartStmt, err = db.PrepareContext(ctx, createCart); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCart: %w", err)
	}
	if q.createMenuItemStmt, err = db.PrepareContext(ctx, createMenuItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMenuItem: %w", err)
	}
	if q.createOrderStmt, err = db.PrepareContext(ctx, createOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrder: %w", err)
	}
	if q.createOrderItemStmt, err = db.PrepareContext(ctx, createOrderItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrderItem: %w", err)
	}
	if q.createRestaurantStmt, err = db.PrepareContext(ctx, createRestaurant); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRestaurant: %w", err)
	}
	if q.deleteMenuItemStmt, err = db.PrepareContext(ctx, deleteMenuItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMenuItem: %w", err)
	}
	if q.deleteRestaurantStmt, err = db.PrepareContext(ctx, deleteRestaurant); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRestaurant: %w", err)
	}
	if q.findOrderByIdempotencyStmt, err = db.PrepareContext(ctx, findOrderByIdempotency); err != nil {
		return nil, fmt.Errorf("error preparing query FindOrderByIdempotency: %w", err)
	}
	if q.getAllRestaurantsStmt, err = db.PrepareContext(ctx, getAllRestaurants); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllRestaurants: %w", err)
	}
	if q.getCartByUserIDStmt, err = db.PrepareContext(ctx, getCartByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartByUserID: %w", err)
	}
	if q.getCartItemsByCartIDStmt, err = db.PrepareContext(ctx, getCartItemsByCartID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCartItemsByCartID: %w", err)
	}
	if q.getMenuItemByIDStmt, err = db.PrepareContext(ctx, getMenuItemByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMenuItemByID: %w", err)
	}
	if q.getMenuItemsByIDsStmt, err = db.PrepareContext(ctx, getMenuItemsByIDs); err != nil {
		return nil, fmt.Errorf("error preparing query GetMenuItemsByIDs: %w", err)
	}
	if q.getMenuItemsByRestaurantIDStmt, err = db.PrepareContext(ctx, getMenuItemsByRestaurantID); err != nil {
		return nil, fmt.Errorf("error preparing query GetMenuItemsByRestaurantID: %w", err)
	}
	if q.getOrderByIDStmt, err = db.PrepareContext(ctx, getOrderByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderByID: %w", err)
	}
	if q.getOrderCountStmt, err = db.PrepareContext(ctx, getOrderCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderCount: %w", err)
	}
	if q.getOrderItemsStmt, err = db.PrepareContext(ctx, getOrderItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItems: %w", err)
	}
	if q.getPaymentByOrderIDStmt, err = db.PrepareContext(ctx, getPaymentByOrderID); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaymentByOrderID: %w", err)
	}
	if q.getPaymentByProviderReferenceStmt, err = db.PrepareContext(ctx, getPaymentByProviderReference); err != nil {
		return nil, fmt.Errorf("error preparing query GetPaymentByProviderReference: %w", err)
	}
	if q.getRestaurantByIDStmt, err = db.PrepareContext(ctx, getRestaurantByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetRestaurantByID: %w", err)
	}
	if q.getUserOrdersStmt, err = db.PrepareContext(ctx, getUserOrders); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserOrders: %w", err)
	}
	if q.insertPaymentStmt, err = db.PrepareContext(ctx, insertPayment); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPayment: %w", err)
	}
	if q.removeCartItemStmt, err = db.PrepareContext(ctx, removeCartItem); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveCartItem: %w", err)
	}
	if q.updateCartItemQuantityStmt, err = db.PrepareContext(ctx, updateCartItemQuantity); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCartItemQuantity: %w", err)
	}
	if q.updateMenuItemStmt, err = db.PrepareContext(ctx, updateMenuItem); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMenuItem: %w", err)
	}
	if q.updateMenuItemAvailabilityStmt, err = db.PrepareContext(ctx, updateMenuItemAvailability); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMenuItemAvailability: %w", err)
	}
	if q.updateOrderPaymentAndStatusStmt, err = db.PrepareContext(ctx, updateOrderPaymentAndStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderPaymentAndStatus: %w", err)
	}
	if q.updatePaymentStatusStmt, err = db.PrepareContext(ctx, updatePaymentStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePaymentStatus: %w", err)
	}
	if q.updateRestaurantStmt, err = db.PrepareContext(ctx, updateRestaurant); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRestaurant: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addCartItemStmt != nil {
		if cerr := q.addCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addCartItemStmt: %w", cerr)
		}
	}
	if q.clearCartStmt != nil {
		if cerr := q.clearCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearCartStmt: %w", cerr)
		}
	}
	if q.createCartStmt != nil {
		if cerr := q.createCartStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCartStmt: %w", cerr)
		}
	}
	if q.createMenuItemStmt != nil {
		if cerr := q.createMenuItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMenuItemStmt: %w", cerr)
		}
	}
	if q.createOrderStmt != nil {
		if cerr := q.createOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderStmt: %w", cerr)
		}
	}
	if q.createOrderItemStmt != nil {
		if cerr := q.createOrderItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderItemStmt: %w", cerr)
		}
	}
	if q.createRestaurantStmt != nil {
		if cerr := q.createRestaurantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRestaurantStmt: %w", cerr)
		}
	}
	if q.deleteMenuItemStmt != nil {
		if cerr := q.deleteMenuItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMenuItemStmt: %w", cerr)
		}
	}
	if q.deleteRestaurantStmt != nil {
		if cerr := q.deleteRestaurantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRestaurantStmt: %w", cerr)
		}
	}
	if q.findOrderByIdempotencyStmt != nil {
		if cerr := q.findOrderByIdempotencyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findOrderByIdempotencyStmt: %w", cerr)
		}
	}
	if q.getAllRestaurantsStmt != nil {
		if cerr := q.getAllRestaurantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllRestaurantsStmt: %w", cerr)
		}
	}
	if q.getCartByUserIDStmt != nil {
		if cerr := q.getCartByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartByUserIDStmt: %w", cerr)
		}
	}
	if q.getCartItemsByCartIDStmt != nil {
		if cerr := q.getCartItemsByCartIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCartItemsByCartIDStmt: %w", cerr)
		}
	}
	if q.getMenuItemByIDStmt != nil {
		if cerr := q.getMenuItemByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMenuItemByIDStmt: %w", cerr)
		}
	}
	if q.getMenuItemsByIDsStmt != nil {
		if cerr := q.getMenuItemsByIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMenuItemsByIDsStmt: %w", cerr)
		}
	}
	if q.getMenuItemsByRestaurantIDStmt != nil {
		if cerr := q.getMenuItemsByRestaurantIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMenuItemsByRestaurantIDStmt: %w", cerr)
		}
	}
	if q.getOrderByIDStmt != nil {
		if cerr := q.getOrderByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderByIDStmt: %w", cerr)
		}
	}
	if q.getOrderCountStmt != nil {
		if cerr := q.getOrderCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderCountStmt: %w", cerr)
		}
	}
	if q.getOrderItemsStmt != nil {
		if cerr := q.getOrderItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsStmt: %w", cerr)
		}
	}
	if q.getPaymentByOrderIDStmt != nil {
		if cerr := q.getPaymentByOrderIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaymentByOrderIDStmt: %w", cerr)
		}
	}
	if q.getPaymentByProviderReferenceStmt != nil {
		if cerr := q.getPaymentByProviderReferenceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPaymentByProviderReferenceStmt: %w", cerr)
		}
	}
	if q.getRestaurantByIDStmt != nil {
		if cerr := q.getRestaurantByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRestaurantByIDStmt: %w", cerr)
		}
	}
	if q.getUserOrdersStmt != nil {
		if cerr := q.getUserOrdersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserOrdersStmt: %w", cerr)
		}
	}
	if q.insertPaymentStmt != nil {
		if cerr := q.insertPaymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPaymentStmt: %w", cerr)
		}
	}
	if q.removeCartItemStmt != nil {
		if cerr := q.removeCartItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeCartItemStmt: %w", cerr)
		}
	}
	if q.updateCartItemQuantityStmt != nil {
		if cerr := q.updateCartItemQuantityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCartItemQuantityStmt: %w", cerr)
		}
	}
	if q.updateMenuItemStmt != nil {
		if cerr := q.updateMenuItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMenuItemStmt: %w", cerr)
		}
	}
	if q.updateMenuItemAvailabilityStmt != nil {
		if cerr := q.updateMenuItemAvailabilityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMenuItemAvailabilityStmt: %w", cerr)
		}
	}
	if q.updateOrderPaymentAndStatusStmt != nil {
		if cerr := q.updateOrderPaymentAndStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderPaymentAndStatusStmt: %w", cerr)
		}
	}
	if q.updatePaymentStatusStmt != nil {
		if cerr := q.updatePaymentStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePaymentStatusStmt: %w", cerr)
		}
	}
	if q.updateRestaurantStmt != nil {
		if cerr := q.updateRestaurantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRestaurantStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	addCartItemStmt                   *sql.Stmt
	clearCartStmt                     *sql.Stmt
	createCartStmt                    *sql.Stmt
	createMenuItemStmt                *sql.Stmt
	createOrderStmt                   *sql.Stmt
	createOrderItemStmt               *sql.Stmt
	createRestaurantStmt              *sql.Stmt
	deleteMenuItemStmt                *sql.Stmt
	deleteRestaurantStmt              *sql.Stmt
	findOrderByIdempotencyStmt        *sql.Stmt
	getAllRestaurantsStmt             *sql.Stmt
	getCartByUserIDStmt               *sql.Stmt
	getCartItemsByCartIDStmt          *sql.Stmt
	getMenuItemByIDStmt               *sql.Stmt
	getMenuItemsByIDsStmt             *sql.Stmt
	getMenuItemsByRestaurantIDStmt    *sql.Stmt
	getOrderByIDStmt                  *sql.Stmt
	getOrderCountStmt                 *sql.Stmt
	getOrderItemsStmt                 *sql.Stmt
	getPaymentByOrderIDStmt           *sql.Stmt
	getPaymentByProviderReferenceStmt *sql.Stmt
	getRestaurantByIDStmt             *sql.Stmt
	getUserOrdersStmt                 *sql.Stmt
	insertPaymentStmt                 *sql.Stmt
	removeCartItemStmt                *sql.Stmt
	updateCartItemQuantityStmt        *sql.Stmt
	updateMenuItemStmt                *sql.Stmt
	updateMenuItemAvailabilityStmt    *sql.Stmt
	updateOrderPaymentAndStatusStmt   *sql.Stmt
	updatePaymentStatusStmt           *sql.Stmt
	updateRestaurantStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		addCartItemStmt:                   q.addCartItemStmt,
		clearCartStmt:                     q.clearCartStmt,
		createCartStmt:                    q.createCartStmt,
		createMenuItemStmt:                q.createMenuItemStmt,
		createOrderStmt:                   q.createOrderStmt,
		createOrderItemStmt:               q.createOrderItemStmt,
		createRestaurantStmt:              q.createRestaurantStmt,
		deleteMenuItemStmt:                q.deleteMenuItemStmt,
		deleteRestaurantStmt:              q.deleteRestaurantStmt,
		findOrderByIdempotencyStmt:        q.findOrderByIdempotencyStmt,
		getAllRestaurantsStmt:             q.getAllRestaurantsStmt,
		getCartByUserIDStmt:               q.getCartByUserIDStmt,
		getCartItemsByCartIDStmt:          q.getCartItemsByCartIDStmt,
		getMenuItemByIDStmt:               q.getMenuItemByIDStmt,
		getMenuItemsByIDsStmt:             q.getMenuItemsByIDsStmt,
		getMenuItemsByRestaurantIDStmt:    q.getMenuItemsByRestaurantIDStmt,
		getOrderByIDStmt:                  q.getOrderByIDStmt,
		getOrderCountStmt:                 q.getOrderCountStmt,
		getOrderItemsStmt:                 q.getOrderItemsStmt,
		getPaymentByOrderIDStmt:           q.getPaymentByOrderIDStmt,
		getPaymentByProviderReferenceStmt: q.getPaymentByProviderReferenceStmt,
		getRestaurantByIDStmt:             q.getRestaurantByIDStmt,
		getUserOrdersStmt:                 q.getUserOrdersStmt,
		insertPaymentStmt:                 q.insertPaymentStmt,
		removeCartItemStmt:                q.removeCartItemStmt,
		updateCartItemQuantityStmt:        q.updateCartItemQuantityStmt,
		updateMenuItemStmt:                q.updateMenuItemStmt,
		updateMenuItemAvailabilityStmt:    q.updateMenuItemAvailabilityStmt,
		updateOrderPaymentAndStatusStmt:   q.updateOrderPaymentAndStatusStmt,
		updatePaymentStatusStmt:           q.updatePaymentStatusStmt,
		updateRestaurantStmt:              q.updateRestaurantStmt,
	}
}
