// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Cart struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type CartItem struct {
	ID         uuid.UUID     `json:"id"`
	CartID     uuid.NullUUID `json:"cart_id"`
	MenuItemID uuid.NullUUID `json:"menu_item_id"`
	Quantity   int32         `json:"quantity"`
	PriceCents int32         `json:"price_cents"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type MenuItem struct {
	ID           uuid.UUID      `json:"id"`
	RestaurantID uuid.NullUUID  `json:"restaurant_id"`
	CategoryID   uuid.NullUUID  `json:"category_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	PriceCents   int32          `json:"price_cents"`
	IsAvailable  sql.NullBool   `json:"is_available"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Order struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.NullUUID  `json:"user_id"`
	RestaurantID     uuid.NullUUID  `json:"restaurant_id"`
	TotalCents       int32          `json:"total_cents"`
	Status           string         `json:"status"`
	IdempotencyKey   sql.NullString `json:"idempotency_key"`
	PaymentProvider  sql.NullString `json:"payment_provider"`
	PaymentReference sql.NullString `json:"payment_reference"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type OrderItem struct {
	ID         uuid.UUID     `json:"id"`
	OrderID    uuid.NullUUID `json:"order_id"`
	MenuItemID uuid.NullUUID `json:"menu_item_id"`
	Quantity   int32         `json:"quantity"`
	PriceCents int32         `json:"price_cents"`
	CreatedAt  sql.NullTime  `json:"created_at"`
}

type Payment struct {
	ID                uuid.UUID             `json:"id"`
	OrderID           uuid.NullUUID         `json:"order_id"`
	Provider          sql.NullString        `json:"provider"`
	ProviderReference sql.NullString        `json:"provider_reference"`
	AmountCents       sql.NullInt32         `json:"amount_cents"`
	Status            sql.NullString        `json:"status"`
	RawPayload        pqtype.NullRawMessage `json:"raw_payload"`
	CreatedAt         sql.NullTime          `json:"created_at"`
}

type Restaurant struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Address     sql.NullString `json:"address"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         sql.NullString `json:"name"`
	Phone        sql.NullString `json:"phone"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}
